
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASTERISK COMMA DELETE EQUALS FROM GREATER IDENTIFIER INSERT INTO LESS LPAREN NUMBER OR RPAREN SELECT SEMICOLON SET STRING UPDATE VALUES WHEREstatement : SELECT columns FROM table WHERE conditions eos\n                     | SELECT columns FROM table eos\n                     | SELECT ASTERISK FROM table WHERE conditions eos\n                     | SELECT ASTERISK FROM table eosstatement : INSERT INTO table VALUES LPAREN values RPAREN eosstatement : UPDATE table SET set_clauses WHERE conditions eos\n                      | UPDATE table SET set_clauses eosstatement : DELETE FROM table WHERE conditions eos\n                      | DELETE FROM table eoscolumns : columns COMMA column\n                   | columncolumn : IDENTIFIERtable : STRINGvalues : values COMMA value\n                  | valuevalue : NUMBER\n                 | STRINGset_clauses : set_clauses COMMA set_clause\n                       | set_clauseset_clause : column EQUALS valueconditions : conditions logical condition\n                      | conditioncondition : column EQUALS value\n                      | column GREATER value\n                      | column LESS valuelogical : AND\n                   | OReos : SEMICOLON'
    
_lr_action_items = {'SELECT':([0,],[2,]),'INSERT':([0,],[3,]),'UPDATE':([0,],[4,]),'DELETE':([0,],[5,]),'$end':([1,28,29,31,33,36,51,58,59,62,67,],[0,-9,-28,-2,-4,-7,-8,-1,-3,-6,-5,]),'ASTERISK':([2,],[7,]),'IDENTIFIER':([2,15,18,27,30,32,35,37,52,53,54,],[9,9,9,9,9,9,9,9,9,-26,-27,]),'INTO':([3,],[10,]),'STRING':([4,10,13,14,16,34,38,55,56,57,61,],[12,12,12,12,12,47,47,47,47,47,47,]),'FROM':([5,6,7,8,9,21,],[13,14,16,-11,-12,-10,]),'COMMA':([6,8,9,21,24,25,44,45,46,47,49,50,68,],[15,-11,-12,-10,37,-19,61,-15,-16,-17,-18,-20,-14,]),'EQUALS':([9,26,41,],[-12,38,55,]),'GREATER':([9,41,],[-12,56,]),'LESS':([9,41,],[-12,57,]),'SET':([11,12,],[18,-13,]),'VALUES':([12,17,],[-13,23,]),'WHERE':([12,19,20,22,24,25,46,47,49,50,],[-13,27,30,32,35,-19,-16,-17,-18,-20,]),'SEMICOLON':([12,19,20,22,24,25,39,40,42,43,46,47,48,49,50,60,63,64,65,66,],[-13,29,29,29,29,-19,29,-22,29,29,-16,-17,29,-18,-20,29,-21,-23,-24,-25,]),'LPAREN':([23,],[34,]),'NUMBER':([34,38,55,56,57,61,],[46,46,46,46,46,46,]),'AND':([39,40,42,43,46,47,48,63,64,65,66,],[53,-22,53,53,-16,-17,53,-21,-23,-24,-25,]),'OR':([39,40,42,43,46,47,48,63,64,65,66,],[54,-22,54,54,-16,-17,54,-21,-23,-24,-25,]),'RPAREN':([44,45,46,47,68,],[60,-15,-16,-17,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'columns':([2,],[6,]),'column':([2,15,18,27,30,32,35,37,52,],[8,21,26,41,41,41,41,26,41,]),'table':([4,10,13,14,16,],[11,17,19,20,22,]),'set_clauses':([18,],[24,]),'set_clause':([18,37,],[25,49,]),'eos':([19,20,22,24,39,42,43,48,60,],[28,31,33,36,51,58,59,62,67,]),'conditions':([27,30,32,35,],[39,42,43,48,]),'condition':([27,30,32,35,52,],[40,40,40,40,63,]),'values':([34,],[44,]),'value':([34,38,55,56,57,61,],[45,50,64,65,66,68,]),'logical':([39,42,43,48,],[52,52,52,52,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> SELECT columns FROM table WHERE conditions eos','statement',7,'p_statement_select','SQLParser.py',14),
  ('statement -> SELECT columns FROM table eos','statement',5,'p_statement_select','SQLParser.py',15),
  ('statement -> SELECT ASTERISK FROM table WHERE conditions eos','statement',7,'p_statement_select','SQLParser.py',16),
  ('statement -> SELECT ASTERISK FROM table eos','statement',5,'p_statement_select','SQLParser.py',17),
  ('statement -> INSERT INTO table VALUES LPAREN values RPAREN eos','statement',8,'p_statement_insert','SQLParser.py',24),
  ('statement -> UPDATE table SET set_clauses WHERE conditions eos','statement',7,'p_statement_update','SQLParser.py',30),
  ('statement -> UPDATE table SET set_clauses eos','statement',5,'p_statement_update','SQLParser.py',31),
  ('statement -> DELETE FROM table WHERE conditions eos','statement',6,'p_statement_delete','SQLParser.py',38),
  ('statement -> DELETE FROM table eos','statement',4,'p_statement_delete','SQLParser.py',39),
  ('columns -> columns COMMA column','columns',3,'p_columns','SQLParser.py',45),
  ('columns -> column','columns',1,'p_columns','SQLParser.py',46),
  ('column -> IDENTIFIER','column',1,'p_column','SQLParser.py',53),
  ('table -> STRING','table',1,'p_table','SQLParser.py',57),
  ('values -> values COMMA value','values',3,'p_values','SQLParser.py',61),
  ('values -> value','values',1,'p_values','SQLParser.py',62),
  ('value -> NUMBER','value',1,'p_value','SQLParser.py',69),
  ('value -> STRING','value',1,'p_value','SQLParser.py',70),
  ('set_clauses -> set_clauses COMMA set_clause','set_clauses',3,'p_set_clauses','SQLParser.py',74),
  ('set_clauses -> set_clause','set_clauses',1,'p_set_clauses','SQLParser.py',75),
  ('set_clause -> column EQUALS value','set_clause',3,'p_set_clause','SQLParser.py',82),
  ('conditions -> conditions logical condition','conditions',3,'p_conditions','SQLParser.py',86),
  ('conditions -> condition','conditions',1,'p_conditions','SQLParser.py',87),
  ('condition -> column EQUALS value','condition',3,'p_condition','SQLParser.py',94),
  ('condition -> column GREATER value','condition',3,'p_condition','SQLParser.py',95),
  ('condition -> column LESS value','condition',3,'p_condition','SQLParser.py',96),
  ('logical -> AND','logical',1,'p_logical','SQLParser.py',100),
  ('logical -> OR','logical',1,'p_logical','SQLParser.py',101),
  ('eos -> SEMICOLON','eos',1,'p_eos','SQLParser.py',105),
]
